### PR TITLE
fix(wrapper): support for node as string

### LINKED ISSUE #11: node is not attached to fixture when mounting as string
If we wanna test attribute propagation to props via string like this
```
mount(
 `<bl-tooltip lable="Im so bored"></bl-tooltip>`
).wait(/*...*/)
```

it throws error.

This is caused by programatic error here
https://github.com/treshugart/bore/blob/master/src/index.js#L84

which should be 
```diff
-fixture.appendChild(node); // node is undefined
+fixture.appendChild(this.node);
```

### PR DESCRIPTION
**Pull request by hopkins-tk**
Fixes #11

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -81,7 +82,12 @@ class Wrapper {
 
     // Add the node to the fixture so it runs the connectedCallback().
     if (isRootNode) {
-      fixture.appendChild(node);
+      if (isStringNode) {
+          fixture.innerHTML = this.node.outerHTML;
```
Comment (hopkins-tk) [inline src/index.js]: Alternatively could be:
```
fixture.innerHTML = node;
```

but we need `nodeFromHtml` to be called anyway as we need to retrieve `customElementDefinition`.

**Comment by devopsmariocom** [comment]
please can you add test so we have string html covered 😉

**Comment by hopkins-tk** [comment]
Test added + running of tests added when running `npm test`

File: .travis.yml [hunk 2]
```diff
@@ -1,8 +1,10 @@
-sudo: false
+sudo: required
```
Comment (hopkins-tk) [inline .travis.yml]: Needed so that newer Firefox can be installed using addon.

File: src/index.js [hunk 3]
```diff
@@ -54,35 +54,35 @@ function matches (node, query) {
...
+
+      if (isStringNode) {
+          fixture.innerHTML = node;
+          this.node = fixture.firstElementChild;
+      } else {
+          fixture.appendChild(node);
+          this.node = node;
+      }
+
+      const customElementDefinition = customElements.get(this.node.localName);
```
Comment (Hotell) [inline src/index.js]: why did you move this to bottom, it makes the code confusing, `const` should be always on top.

File: src/index.js [hunk 4]
```diff
@@ -54,34 +54,34 @@ function matches (node, query) {
...
+    const isStringNode = typeof node === 'string';
     const isRootNode = !node.parentNode;
 
+    // If the fixture has been removed from the document, re-insert it.
+    if (!body.contains(fixture)) {
+      body.appendChild(fixture);
+    }
+
     // If this is a new node, clean up the fixture.
     if (isRootNode) {
```
Comment (Hotell) [inline src/index.js]: lets wrap it within a function.

Let's say smthng like this:

```js
function getInstantiatedNodeWithinFixture(node, isRootNode) {

  const isStringNode = typeof node === 'string';

  // If the fixture has been removed from the document, re-insert it.
  if (!body.contains(fixture)) {
    body.appendChild(fixture);
  }

  // If this is a new node, clean up the fixture.
  if (isRootNode) {
    setFixtureContent();
  }

  return isStringNode 
    ? fixture.firstElementChild 
    : node;

  function setFixtureContent() {

    // If this is a new node, clean up the fixture.
    fixture.innerHTML = '';

    // Add the node to the fixture so it runs the connectedCallback().
    return isStringNode 
      ? (fixture.innerHTML = node) 
      : (fixture.appendChild(node));
  }
}

class Wrapper {
  constructor(node, opts = {}) {

    const isRootNode = !node.parentNode;

    this.opts = opts;
    this.node = getInstantiatedNodeWithinFixture(node, isRootNode);

    if (isRootNode) {
      const customElementDefinition = customElements.get(this.node.localName);
      customElementDefinition && flush();
    }
  }
}
```

**Review by Hotell — CHANGES_REQUESTED** [review]

**Review by Hotell — APPROVED** [review]
LGTM. good job! can you review pls @treshugart

File: .travis.yml (hunk 2 above)
Comment (treshugart) [reply .travis.yml]: Interesting, this should be running in Sauce Labs, so you shouldn't need this. I'd prefer to not have to do this and fix the sauce issue.

File: test/unit.js [hunk 5]
```diff
@@ -116,6 +116,20 @@ describe('bore', () => {
     expect(test.all('span').length).to.equal(1);
     expect(test.all('span')[0].node.localName).to.equal('span');
   });
+
+  it('mount: should descend for node as string into custom elements', () => {
+    class Test extends HTMLElement {
+      connectedCallback () {
+        this.attachShadow({ mode: 'open' });
```
Comment (treshugart) [inline test/unit.js]: Just as a note, `bore` forces `open` shadow roots, so you don't need this.

File: src/index.js [hunk 6]
```diff
@@ -54,34 +54,42 @@ function matches (node, query) {
...
+
+  if (isRootNode) {
+    setFixtureContent();
+  }
+
+  return isStringNode
+    ? fixture.firstElementChild
+    : node;
+
+  function setFixtureContent() {
```
Comment (treshugart) [inline src/index.js]: What do you think about moving this into the parent scope and passing in `node` to it. Also, the return value doesn't seem to be used anywhere. Can we just not return anything for clarity?

File: test/unit.js [hunk 7]
```diff
@@ -116,6 +116,20 @@ describe('bore', () => {
...
+        this.shadowRoot.innerHTML = '<span></span>';
+      }
+    }
+    customElements.define('x-mount-test-2', Test);
+    return mount('<x-mount-test-2></x-mount-test-2>').wait((element) => {
```
Comment (treshugart) [inline test/unit.js]: You shouldn't have to `wait` here. That's only for libs like Skate that have async rendering.

**Review by treshugart — CHANGES_REQUESTED** [review]
Mostly nits, but would at least like the changes for `setFixtureContent()` to be made. Thanks!

File: test/unit.js (hunk 7 above)
Comment (Hotell) [reply test/unit.js]: that's indeed good to know. thanks @treshugart  !

File: src/index.js [hunk 8]
```diff
@@ -54,34 +54,44 @@ function matches (node, query) {
...
+  if (isRootNode) {
+    setFixtureContent( node );
+  }
+
+  return isStringNode
+    ? fixture.firstElementChild
+    : node;
+}
+
+function setFixtureContent( node ) {
```
Comment (Hotell) [inline src/index.js]: just a nit pick.

we are using 2 times the same operation ` const isStringNode = typeof node === 'string';`

maybe we can make it more DRY like this:

```js
function getInstantiatedNodeWithinFixture(node, isRootNode) {
  const isStringNode = typeof node === 'string';

  // If the fixture has been removed from the document, re-insert it.
  if (!body.contains(fixture)) {
    body.appendChild(fixture);
  }

  if (isRootNode) {
    setFixtureContent( node, isStringNode );
  }

  return isStringNode
    ? fixture.firstElementChild
    : node;
}

function setFixtureContent( node, shouldSetChildrenViaString ) {    

    // If this is a new node, clean up the fixture.
    fixture.innerHTML = '';

    // Add the node to the fixture so it runs the connectedCallback().
    shouldSetChildrenViaString
        ? (fixture.innerHTML = node)
        : (fixture.appendChild(node));
}
```

WDYT? otherwise LGTM! thx!

**Review by Hotell — CHANGES_REQUESTED** [review]

**Review by Hotell — APPROVED** [review]
thx!

File: src/index.js [hunk 9]
```diff
@@ -54,34 +54,42 @@ function matches (node, query) {
...
+  if (isRootNode) {
+    setFixtureContent( node, isStringNode );
+  }
+
+  return isStringNode
+    ? fixture.firstElementChild
+    : node;
+}
+
+function setFixtureContent( node, shouldSetChildrenViaString ) {
```
Comment (treshugart) [inline src/index.js]: Did semistandard not catch this? If not we should see why.

Function declaration should look like this: `function setFixtureContent (node, shouldSetChildrenViaString) {`

File: src/index.js [hunk 10]
```diff
@@ -54,34 +54,42 @@ function matches (node, query) {
...
+    // If this is a new node, clean up the fixture.
+    fixture.innerHTML = '';
+
+    // Add the node to the fixture so it runs the connectedCallback().
+    shouldSetChildrenViaString
+        ? (fixture.innerHTML = node)
```
Comment (treshugart) [inline src/index.js]: Indentation here should be 2 spaces.

**Comment by treshugart** [comment]
Sorry for the codestyle nits. Semistandard should have caught it. Not sure why it didn't. Approved pending these are fixed :)

**Review by treshugart — APPROVED** [review]

File: src/index.js (hunk 9 above)
Comment (Hotell) [reply src/index.js]: about semistandard. I know it's installed via `skate/build` package, but, if user want's to fix lint errors, `sk-lint -- --fix` just doesn't work and user has to manually install semistandard to run those fixes ( it's not very convenient to fix those manually ). Maybe we should create `sk-lint-fix` command withing `skate/build` package and also add git pre commit hooks which will run tests/lint so we don't have to deal with these kind of problems during PRs. WDYT?

**Comment by treshugart** [comment]
Sure.

**Comment by Hotell** [comment]
there it is @treshugart  https://github.com/skatejs/build/pull/494
